name: flappy_bird
description: Flappy Bird Game

publish_to: 'none'

version: 1.0.0+1
homepage: tguzel.dev
repository: https://github.com/tyypgzl/flappy-bird

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  audioplayers: ^1.0.1
  cupertino_icons: ^1.0.2
  flame: ^1.3.0
  flame_audio: ^1.3.1

  flutter:
    sdk: flutter


dev_dependencies:
  flame_lint: ^0.1.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/FlappyBirdy.ttf
    - assets/audio/

  fonts:
    - family: FlappyBird
      fonts:
        - asset: assets/fonts/FlappyBirdy.ttf
